import Footer from '@/components/templates/Footer';
import Navbar from '@/components/templates/Navbar';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { SpeedInsights } from '@vercel/speed-insights/next';
const iranSans = localFont({
  src: '../public/fonts/woff/IRANSansX-Black.woff',
});

export const metadata: Metadata = {
  title: ' Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang='fa' dir='rtl'>
      <body
        className={`${iranSans} ${iranSans} antialiased max-w-[1550px] mx-auto`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
